<#--<!DOCTYPE html>-->
<#--<html lang="en">-->
<#--<head>-->
<#--    <meta charset="UTF-8">-->
<#--    <title>Save Method Test</title>-->
<#--</head>-->
<#--<body>-->
<#--<form action="/save" method="POST">-->
<#--    <label for="text">Text:</label>-->
<#--    <input type="text" id="text" name="text" required>-->
<#--    <button type="submit">Save</button>-->
<#--</form>-->
<#--</body>-->
<#--</html>-->